before:
  hooks:
    - go mod tidy
builds:
  - ldflags:
      - -X 'main.buildVersion={{.Version}}'
    env:
      - CGO_ENABLED=0
    # https://pkg.go.dev/modernc.org/sqlite#hdr-Supported_platforms_and_architectures
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm64
      - arm
      - 386 
    ignore:
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: 386
      - goos: freebsd
        goarch: arm64
      - goos: freebsd
        goarch: arm
      - goos: freebsd
        goarch: 386
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: 386
archives:
  - replacements:
      386: i386
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
# dockers:
#   - image_templates:
#     - "gcr.io/rssnyder/discord-stock-ticker:latest"
#     - "gcr.io/rssnyder/discord-stock-ticker:{{ .Tag }}"
#     build_flag_templates:
#     - "--label=org.opencontainers.image.created={{.Date}}"
#     - "--label=org.opencontainers.image.title={{.ProjectName}}"
#     - "--label=org.opencontainers.image.revision={{.FullCommit}}"
#     - "--label=org.opencontainers.image.version={{.Version}}"
#     - "--label=org.opencontainers.image.source={{.GitURL}}"
