on:
  workflow_dispatch:
  pull_request:
  release:
    types:
      - published

permissions:
  contents: write
  packages: write

jobs:
  go:
    uses: rssnyder/actions/.github/workflows/go-releaser.yml@main
    with:
      go-version: 1.19
  docker:
    needs: go
    uses: rssnyder/actions/.github/workflows/docker-build-and-push.yml@main
